name: responsive_units
description: A Flutter package that provides responsive units that scale with the device's screen size.
version: 0.1.1
homepage: https://github.com/peter-sidra/responsive_units
repository: https://github.com/peter-sidra/responsive_units

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
